# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'hounddd.testbatches::lang.models.job.label'

# Model Form Field configuration
form: $/hounddd/testbatches/models/job/fields.yaml

# Model Class name
modelClass: Hounddd\TestBatches\Models\Job

# Default redirect location
defaultRedirect: hounddd/testbatches/jobs

# Create page
create:
    title: backend::lang.form.create_title
    redirect: hounddd/testbatches/jobs/update/:id
    redirectClose: hounddd/testbatches/jobs

# Update page
update:
    title: backend::lang.form.update_title
    redirect: hounddd/testbatches/jobs
    redirectClose: hounddd/testbatches/jobs

# Preview page
preview:
    title: backend::lang.form.preview_title
