# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'hounddd.testbatches::lang.models.batch.label'

# Model Form Field configuration
form: $/hounddd/testbatches/models/batch/fields.yaml

# Model Class name
modelClass: Hounddd\TestBatches\Models\Batch

# Default redirect location
defaultRedirect: hounddd/testbatches/batches

# Create page
create:
    title: backend::lang.form.create_title
    redirect: hounddd/testbatches/batches/update/:id
    redirectClose: hounddd/testbatches/batches

# Update page
update:
    title: backend::lang.form.update_title
    redirect: hounddd/testbatches/batches
    redirectClose: hounddd/testbatches/batches

# Preview page
preview:
    title: backend::lang.form.preview_title
